### ISSUE TITLE
Regarding MySQL, Player data does not sync

### ISSUE THREAD

**Issue by notbike** [Rocologo/BagOfGold#105]
Hi, Probably my misconfiguration, but I just finished setting up my MySQL for my 2 test servers. the consoles showed the bagofgold is connected to the MySQL, but it's showing different balance in different servers. It seems like even though both of them are connected to MySQL, only one has access to it, since one of the server made changes to it.

I have no idea how to fix this, both bagofgold are the latest build, both folders are identical, since i copied and pasted them.

here are my configs, I did not change any of the default settings except the database section:

[bagofgoldcore](https://pastebin.com/ywKGFPfX)
[bagofgoldconfig](https://pastebin.com/Gs6FpejJ)

Thank you good sir! Love both of your plugins!

**Comment by notbike** [comment]
i tested with other economy plugins, and it works fine between servers.

**Comment by Rocologo** [comment]
Hi, what others plugins can do, has of cause nothing to do with what this plugin can do ;-) If you dive into other eConomy plugins, they have limitations too. 

What you are trying to do is unfortunately not possible BogOfGold. The problem is that the player balance and transactions is saved in to memory first and the saved to disk/database later (every 10th minut) to make the plugin very fast. Disk/database access is always slow. When you have one player online this is not a problem, but if you have many many players they would start to see lags because of slow disk access. 

This means that your second server should be able to get the balance from the first ones memory (and not from the shared database) and this is not possible. I think a Bungee network is able to share some stuff, but I have NO idea about how to do this and I can find any tutorials.

**Comment by notbike** [comment]
i see, this is really unfortunate. But not a deal breaker. I really love this plugin, of course not as much as i love my gf.
