### ISSUE TITLE
Banking signs

### ISSUE THREAD

**Issue by festation2003** [Rocologo/BagOfGold#127]
In the write up's you have an image of signs to interact with the bank, well i have been going round in circles trying to work out how to actually create them to be able to give bedrock players access to the banking system (bedrock cant interact with chat to use the npc banker)

If there is a command im missing, please let me know otherwise is there some kind of plan to add this feature?

Thankyou

**Comment by jnijland** [comment]
I'm currently using this feature since the NPC's dont work for me, the sign feature works fine for me. 

On line one you enter the value from ```bank_name_on_sign```in your config.yml file between [ ], so keep in mind the bank name shouldn't be to long. The default value is 'BagOfGold Bank'. 
On line two you enter one of the following values: Deposit, Withdraw or Balance. So which action you want to perform using that sign. 
On the third line you could either declare 'Everything' (e.g. deposit everything, withdraw everything), an amount you want to deposit or withdraw using that sign, or keep the line empty (in case of balance you should keep this line empty).

If the signs don't work, you should confirm whether you have the required permissions in your permission plugin: 
```
bagofgold.banksign.create
bagofgold.banksign.destroy
bagofgold.banksign.use
```

**Comment by rackgaming** [comment]
There seems to be a problem for me using this plugin. I am using GriefPrevention(which idk what that has to do with it) but I give my default players perms bagofgold.banksign.use and nothing happens, it just lags my client side. I am also using Vault. another thing to note is I am also using LuckPerms and if I give myself operator, it works fine.

**Comment by rackgaming** [comment]
I am currently testing this out with vault but oddly enough, one of the signs break when switching from reserve to vault but when using reserve works fine. Those 2 signs are Deposit Everything and Withdraw everything

**Comment by Rocologo** [comment]
The answer is correct. Thank you @jnijland
