### ISSUE TITLE
balance

### ISSUE THREAD

**Issue by Mavhill** [Rocologo/BagOfGold#26]
"if you have Essentials on your server, /bal and /mh money bal will show the same amount of money and you will be able to use the /eco commands."

using essentials with bagofgold 1.17 with latest spigot 1.12

Using /bal or mh money after depositing in bagofgold bank results in 0
While I understand this is somewhat intentional with this set this way any other plug that needs to see money in balance will see a 0 resulting in problems such as shops not working or being deranked due to loss of requirements. /bal top totals are completely changed by this as well.

I understand the intention is to have vulnerable money while carrying the bagofgold and i like this feature however the overall balance of total wealth needs to be seen by other plugs. there needs to be a way to make this work so that /bal and /mh money will allow seeing this total wealth while still having the separation of personal wallet vs bank wallet.
If you intend on adding a balance top or balance total feature to this it will have to be addressed in some fashion otherwise you will have a variance between the lists always that will lead to much player confusion.

**Comment by Rocologo** [comment]
Hi Mavhill

I think we have talked about this before ? :-)

**/bal** and **/baltop** is Essentials commands, and no matter what, I am not able to change how they work. Essentials does NOT support Banks while BagOfGold **does** support Banks. 

It is not possible to change **/bal** or **/mh bag bal** so they would show players balance + players bank balance - this is because the behavior is defined in Vault: 

https://github.com/MilkBowl/VaultAPI/blob/master/src/main/java/net/milkbowl/vault/economy/Economy.java

I cant change this either. I need to stick with vault, because it is vault which makes sure that BagOfGold works with other plugins which need an economy plugin. 

So!!! I can't make changes so **/baltop, /bal, /mh bag bal** show total wealth, also you forget that the player can hide bags in a protected chest, which is hidden from me. Which means that **/baltop** would never show the total wealth anyway.

What is possible is to make two new command **/mh bag wealth  & /mh bag wealthtop** and show you the most wealthy players. I would not call it baltop, because **/mh bag baltop** should show the same as **/baltop**

**Comment by Rocologo** [comment]
PS. does you send data to bStats?

**Comment by Rocologo** [comment]
MC1.13 Only version can be found here:
https://fractal.lindegaard.one:8181/job/BagOfGold/
https://fractal.lindegaard.one:8181/job/MobHunting/
