### ISSUE TITLE
"You can't buy/sell Bag of gold with Bag of gold"

### ISSUE THREAD

**Issue by mobilephone2003** [Rocologo/BagOfGold#27]
Minecraft 1.13
Build #100 of Bag of Gold

Shows the above error when using a "Bag of gold" sell sign with the gold in-hand

**Comment by Rocologo** [comment]
You can of cause not sell BagOfGold and get BagOfGold in return. 

You would never try to sell money for money :-)

BagOfGold is your money. So you cant sell it. 

The BagOfGold sign is made for sell Bags when you dont use the BagOfGold plugin.

But you can use BagOfGold Bank signs instead and put the money in the Bank, so they cant be stolen or list

**Comment by Rocologo** [comment]
I dont understand your question? When you use BagOfGold, it is your currency??? If you drop the bag you have no money, when you pick up the money you have them... Does you use another economy plugin as well?

Få Outlook til iOS<https://aka.ms/o0ukef>

________________________________
Fra: mobilephone2003 <notifications@github.com>
Sendt: lørdag, juli 28, 2018 8:23 AM
Til: Rocologo/BagOfGold
Cc: Rocologo; Comment
Emne: Re: [Rocologo/BagOfGold] "You can't buy/sell Bag of gold with Bag of gold" (#27)

Sell Bag of Gold suggests selling to get game currency, how can we do that?

**Comment by mobilephone2003** [comment]
Yes, the aim is to have the mobs drop the bag of gold and player collect it and go to a sign to sell it for in-game currency through another plugin.

**Comment by Rocologo** [comment]
Which other plugin are we talking about?

Få Outlook til iOS<https://aka.ms/o0ukef>

________________________________
Fra: mobilephone2003 <notifications@github.com>
Sendt: lørdag, juli 28, 2018 9:11 AM
Til: Rocologo/BagOfGold
Cc: Rocologo; Comment
Emne: Re: [Rocologo/BagOfGold] "You can't buy/sell Bag of gold with Bag of gold" (#27)

Yes, the aim is to have the mobs drop the bag of gold and player collect it and go to a sign to sell it for in-game currency through another plugin.

**Comment by mobilephone2003** [comment]
CMI Economy

**Comment by Rocologo** [comment]
If you want another currency than BagOfGold you dont need my BagOfGold plugin

Få Outlook til iOS<https://aka.ms/o0ukef>

________________________________
Fra: mobilephone2003 <notifications@github.com>
Sendt: lørdag, juli 28, 2018 9:13 AM
Til: Rocologo/BagOfGold
Cc: Rocologo; Comment
Emne: Re: [Rocologo/BagOfGold] "You can't buy/sell Bag of gold with Bag of gold" (#27)

CMI Economy

**Comment by mobilephone2003** [comment]
There may be confusion, how do I get the mob to drop the gold head and have it be sold then? I want players to get the bag and take it to a place to get the economy currency.

**Comment by Rocologo** [comment]
MobHunting can do that. Check the dropmoneyonground section in the config.yml

BagOfGold plugin makes the bags to a real Vault supported economy. So it seems you have installed 2 economy currencies. I dont know what happens when you do so. I think i will test this on my test server.

Få Outlook til iOS<https://aka.ms/o0ukef>

________________________________
Fra: Rocologo - <rocologo@hotmail.com>
Sendt: lørdag, juli 28, 2018 9:15 AM
Til: Rocologo/BagOfGold; Rocologo/BagOfGold
Cc: Comment
Emne: Re: [Rocologo/BagOfGold] "You can't buy/sell Bag of gold with Bag of gold" (#27)

If you want another currency than BagOfGold you dont need my BagOfGold plugin

Få Outlook til iOS<https://aka.ms/o0ukef>

________________________________
Fra: mobilephone2003 <notifications@github.com>
Sendt: lørdag, juli 28, 2018 9:13 AM
Til: Rocologo/BagOfGold
Cc: Rocologo; Comment
Emne: Re: [Rocologo/BagOfGold] "You can't buy/sell Bag of gold with Bag of gold" (#27)

CMI Economy
