### ISSUE TITLE
Integration with the ItemFrameShop plugin

### ISSUE THREAD

**Issue by C4BR3R4** [Rocologo/BagOfGold#45]
I would like to use the plugin, but it is incompatible with [ItemFrameShop](https://www.spigotmc.org/resources/itemframeshops.4667/).

![imagen](https://user-images.githubusercontent.com/4703920/47727087-11e32180-dc5c-11e8-9580-de6abfdcedca.png)

**Comment by Rocologo** [comment]
Could you show me the complete server log on restart?

**Comment by C4BR3R4** [comment]
Excuse me, I did not remember that it is a premium plugin.

Can it be that the plugin loads after ItemFrameShops and therefore does not detect that there is an economy plugin?

Start log: https://pastebin.com/HGwY9S3z

**Comment by Rocologo** [comment]
Np. 

But there is a bigger problem. I see you use MC 1.12.2 and I have to admid that BagOfGold is not stable when you have multible worlds and I see that you use Multiverse, so I will not recommend you to use BagOfGold until you are able to upgrade to 1.13.2... Sorry 

I made big changes when I went from BagOfGold 1.1.7 to 2.X - because i realized that I would never be able to make 1.1.7 stable in a multiworld / survival/creative environment...

**Comment by Rocologo** [comment]
and YES you are right. TItemFrameShop is loaded BEFORE BagOfGold. I could probably fix this by changing my plugin.yml and add ItemFromShop to the "loadbefore" list in the yml file the bagofgold.jar file

You could actually try this yourself, this it would not solve the stability problem in 1.1.7

**Comment by Rocologo** [comment]
ItemFrameShops has been added to my plugin.yml file, but only for MC 1.13.2 servers
