### ISSUE TITLE
Unable to drop currency while moving

### ISSUE THREAD

**Issue by Ramoramparo** [Rocologo/BagOfGold#61]
I have noticed that on version 2.5.4 on 1.13.2, if you attempt to move and drop currency out of your inventory, it does not work. You must be standing completely still. Anyway around this?

**Comment by Rocologo** [comment]
I have to test this to see if I can reproduce the problem. Im not sure if I know how to move and drop items at the same time? How do you do this?

**Comment by Ramoramparo** [comment]
I do not know the default key for dropping items, I believe it is "q" however. If it not, go into controls and under the inventory category, the "Drop Selected Item" key is what drops items. 

To specify on the issue, I meant that while moving, using your walk keys "AWSD" and then attempting to click "q" or whatever key you set it to with the Bag of Gold in your hand as the active item, it will not drop. You must be standing still to drop it. Please let me know if you need more clarification. 

Thanks for the quick responses on both of my issues I posted.

**Comment by Rocologo** [comment]
I cant solve this problem. When I drop bags on the ground i drop the bag 1 or 2 blocks in front of the player. This makes things look good, when the player stands still. I cant drop the bag where the player stands, because the the bag is picked up immediately. 

If I drop the money behind the player it looks strange seen from the player perspective.
